export type FormFieldBase = {
    type: string;
    label: string;
    description?: string | null;
    placeholder?: string | null;
    isRequired?: boolean;
    order: number;
    config?: Record<string, unknown>;
};

export type UpdatedField = Partial<FormFieldBase> & { id: string };

export type FormMeta = {
    title?: string;
    description?: string;
};

export type SaveDeltaPayload = {
    formId: string;
    newFields: (FormFieldBase & { tempId: string })[];
    updatedFields: UpdatedField[];
    deletedIds: string[];
    meta?: FormMeta;
};

export type SaveDeltaFunction = (payload: SaveDeltaPayload) => Promise<{ newIds?: Record<string, string> }> | void;

/**
 * Reusable form builder utility to track changes and prepare payloads for useSaveDelta.
 * Framework-agnostic: does not call React hooks, database, tRPC directly, or perform network requests.
 */
export class FormDeltaTracker {
    private formId: string;
    private saveFn: SaveDeltaFunction;
    private debounceMs: number;
    private onSaveSuccess?: (newIds: Record<string, string>) => void;

    // Track state changes
    private _newFields: Map<string, FormFieldBase> = new Map();
    private _updatedFields: Map<string, UpdatedField> = new Map();
    private _deletedIds: Set<string> = new Set();
    private _meta: FormMeta = {};

    private _isDirty = false;
    private _isSaving = false;
    private savePromise: Promise<void> | null = null;
    
    private _lastSavedAt: Date | null = null;
    private timerId: ReturnType<typeof setTimeout> | null = null;

    constructor(
        formId: string, 
        saveFn: SaveDeltaFunction, 
        debounceMs = 10000,
        onSaveSuccess?: (newIds: Record<string, string>) => void
    ) {
        this.formId = formId;
        this.saveFn = saveFn;
        this.debounceMs = debounceMs;
        this.onSaveSuccess = onSaveSuccess;
    }

    get isDirty() {
        return this._isDirty;
    }

    get lastSavedAt() {
        return this._lastSavedAt;
    }

    get pendingDelta(): Omit<SaveDeltaPayload, 'formId'> {
        return {
            newFields: Array.from(this._newFields.entries()).map(([tempId, field]) => ({ ...field, tempId })),
            updatedFields: Array.from(this._updatedFields.values()),
            deletedIds: Array.from(this._deletedIds),
            meta: Object.keys(this._meta).length > 0 ? this._meta : undefined,
        };
    }

    /**
     * Track a newly created field.
     * @param tempId A temporary ID generated by the UI to reference this new field before it gets saved.
     * @param field The field data.
     */
    public trackNewField(tempId: string, field: FormFieldBase) {
        this._newFields.set(tempId, field);
        this.evaluateDirtyState();
    }

    /**
     * Track an update to an existing field or a newly created field.
     * @param id The real ID or temporary ID.
     * @param updates The changes to apply.
     * @param isNew Whether this field is a new field (not yet saved to the backend).
     */
    public trackUpdatedField(id: string, updates: Partial<FormFieldBase>, isNew = false) {
        if (!isNew && this._deletedIds.has(id)) {
            // Deleted field protection: do not track updates for deleted fields
            return;
        }

        if (isNew) {
            const existing = this._newFields.get(id);
            if (existing) {
                this._newFields.set(id, { ...existing, ...updates });
                this.evaluateDirtyState();
            }
        } else {
            const existing = this._updatedFields.get(id) || { id };
            this._updatedFields.set(id, { ...existing, ...updates });
            this.evaluateDirtyState();
        }
    }

    /**
     * Track the deletion of a field.
     * @param id The real ID or temporary ID.
     * @param isNew Whether this field is a new field (not yet saved to the backend).
     */
    public trackDeletedField(id: string, isNew = false) {
        if (isNew) {
            // Remove from tracking entirely since it was never saved
            this._newFields.delete(id);
        } else {
            this._updatedFields.delete(id);
            this._deletedIds.add(id);
        }
        
        this.evaluateDirtyState();
    }

    /**
     * Track a change to the form's metadata.
     */
    public trackMetaChange(meta: Partial<FormMeta>) {
        this._meta = { ...this._meta, ...meta };
        this.evaluateDirtyState();
    }

    private evaluateDirtyState() {
        const hasChanges = this._newFields.size > 0 || 
                           this._updatedFields.size > 0 || 
                           this._deletedIds.size > 0 || 
                           Object.keys(this._meta).length > 0;
                           
        if (hasChanges) {
            this._isDirty = true;
            this.scheduleAutoSave();
        } else {
            this._isDirty = false;
            this.clearTimer();
        }
    }

    private scheduleAutoSave() {
        this.clearTimer();
        this.timerId = setTimeout(() => {
            this.executeSave().catch(() => {});
        }, this.debounceMs);
    }

    private clearTimer() {
        if (this.timerId) {
            clearTimeout(this.timerId);
            this.timerId = null;
        }
    }

    /**
     * Immediately persist pending changes without waiting for the inactivity timer.
     * If the builder is not dirty, no save request is sent.
     */
    public async forceSave() {
        this.clearTimer();
        
        // Wait for any in-progress save to finish to prevent concurrent saves
        while (this._isSaving && this.savePromise) {
            try {
                await this.savePromise;
            } catch (e) {
                // Ignore any failure from the previous save, we will just evaluate and try again
            }
        }
        
        if (!this._isDirty) {
            return;
        }
        
        await this.executeSave();
    }

    private async executeSave(): Promise<void> {
        // Prevent concurrent saves
        if (this._isSaving) {
            return;
        }

        const hasNew = this._newFields.size > 0;
        const hasUpdated = this._updatedFields.size > 0;
        const hasDeleted = this._deletedIds.size > 0;
        const hasMeta = Object.keys(this._meta).length > 0;

        // Double check if there are actual changes
        if (!hasNew && !hasUpdated && !hasDeleted && !hasMeta) {
            this._isDirty = false;
            return;
        }

        const payload: SaveDeltaPayload = {
            formId: this.formId,
            newFields: Array.from(this._newFields.entries()).map(([tempId, field]) => ({ ...field, tempId })),
            updatedFields: Array.from(this._updatedFields.values()),
            deletedIds: Array.from(this._deletedIds),
        };

        if (hasMeta) {
            payload.meta = { ...this._meta };
        }

        // Snapshot current state to clear it before saving
        // This allows new changes to be tracked while the save request is in flight
        const savedNewFieldsEntries = Array.from(this._newFields.entries());
        const savedUpdatedFieldsEntries = Array.from(this._updatedFields.entries());
        const savedDeletedIds = Array.from(this._deletedIds);
        const savedMeta = { ...this._meta };

        // Clear tracked changes
        this._newFields.clear();
        this._updatedFields.clear();
        this._deletedIds.clear();
        this._meta = {};
        
        // We set dirty to false, but it might flip back to true if changes happen during await
        this._isDirty = false;
        this._isSaving = true;


        this.savePromise = (async () => {
            try {
                const result = await this.saveFn(payload);
                this._lastSavedAt = new Date();
                if (result?.newIds && this.onSaveSuccess) {
                    this.onSaveSuccess(result.newIds);
                }
            } catch (error) {
                // Restore the state so changes are not lost on failure
                this.restoreFailedState(savedNewFieldsEntries, savedUpdatedFieldsEntries, savedDeletedIds, savedMeta);
                throw error;
            } finally {
                this._isSaving = false;
                this.savePromise = null;
                
                // If new changes were accumulated during save, we should trigger auto-save again
                if (this._isDirty && !this.timerId) {
                    this.scheduleAutoSave();
                }
            }
        })();

        return this.savePromise;
    }

    private restoreFailedState(
        failedNew: [string, FormFieldBase][],
        failedUpdated: [string, UpdatedField][],
        failedDeleted: string[],
        failedMeta: FormMeta
    ) {
        // Merge failed state back into the current state (prioritizing current state which might have newer changes)
        for (const [id, field] of failedNew) {
            if (!this._newFields.has(id)) {
                this._newFields.set(id, field);
            }
        }

        for (const [id, field] of failedUpdated) {
            if (!this._updatedFields.has(id)) {
                this._updatedFields.set(id, field);
            }
        }

        for (const id of failedDeleted) {
            this._deletedIds.add(id);
        }

        this._meta = { ...failedMeta, ...this._meta };
        this.evaluateDirtyState();
    }

    public destroy() {
        this.clearTimer();
    }
}
